#Database
POSTGRES_SQL_USERNAME: postgres
POSTGRES_SQL_PASSWORD: 5404
POSTGRES_SQL_HOST: 127.0.0.1
POSTGRES_SQL_PORT: 5432
POSTGRES_SQL_DB: spcloud

#Server
SERVER_PORT: 9000
ACTIVE_PROFILE: prod

#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: ozodbek.xomidbekov@gmail.com
EMAIL_PASSWORD: wuoo zvop uqff abfo
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}